/*
CloudFabrix RDA Platform API

CloudFabrix RDA Platform API

API version: 3.2.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cfx_rda_api

import (
	"encoding/json"
)

// checks if the PstreamEditModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PstreamEditModel{}

// PstreamEditModel struct for PstreamEditModel
type PstreamEditModel struct {
	Attributes map[string]interface{} `json:"attributes,omitempty"`
}

// NewPstreamEditModel instantiates a new PstreamEditModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPstreamEditModel() *PstreamEditModel {
	this := PstreamEditModel{}
	return &this
}

// NewPstreamEditModelWithDefaults instantiates a new PstreamEditModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPstreamEditModelWithDefaults() *PstreamEditModel {
	this := PstreamEditModel{}
	return &this
}

// GetAttributes returns the Attributes field value if set, zero value otherwise.
func (o *PstreamEditModel) GetAttributes() map[string]interface{} {
	if o == nil || IsNil(o.Attributes) {
		var ret map[string]interface{}
		return ret
	}
	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PstreamEditModel) GetAttributesOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Attributes) {
		return map[string]interface{}{}, false
	}
	return o.Attributes, true
}

// HasAttributes returns a boolean if a field has been set.
func (o *PstreamEditModel) HasAttributes() bool {
	if o != nil && !IsNil(o.Attributes) {
		return true
	}

	return false
}

// SetAttributes gets a reference to the given map[string]interface{} and assigns it to the Attributes field.
func (o *PstreamEditModel) SetAttributes(v map[string]interface{}) {
	o.Attributes = v
}

func (o PstreamEditModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PstreamEditModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Attributes) {
		toSerialize["attributes"] = o.Attributes
	}
	return toSerialize, nil
}

type NullablePstreamEditModel struct {
	value *PstreamEditModel
	isSet bool
}

func (v NullablePstreamEditModel) Get() *PstreamEditModel {
	return v.value
}

func (v *NullablePstreamEditModel) Set(val *PstreamEditModel) {
	v.value = val
	v.isSet = true
}

func (v NullablePstreamEditModel) IsSet() bool {
	return v.isSet
}

func (v *NullablePstreamEditModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePstreamEditModel(val *PstreamEditModel) *NullablePstreamEditModel {
	return &NullablePstreamEditModel{value: val, isSet: true}
}

func (v NullablePstreamEditModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePstreamEditModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


