/*
CloudFabrix RDA Platform API

CloudFabrix RDA Platform API

API version: 3.2.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cfx_rda_api

import (
	"encoding/json"
)

// checks if the PstreamAddModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PstreamAddModel{}

// PstreamAddModel struct for PstreamAddModel
type PstreamAddModel struct {
	Name string `json:"name"`
	Attributes map[string]interface{} `json:"attributes,omitempty"`
}

// NewPstreamAddModel instantiates a new PstreamAddModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPstreamAddModel(name string) *PstreamAddModel {
	this := PstreamAddModel{}
	this.Name = name
	return &this
}

// NewPstreamAddModelWithDefaults instantiates a new PstreamAddModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPstreamAddModelWithDefaults() *PstreamAddModel {
	this := PstreamAddModel{}
	return &this
}

// GetName returns the Name field value
func (o *PstreamAddModel) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *PstreamAddModel) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *PstreamAddModel) SetName(v string) {
	o.Name = v
}

// GetAttributes returns the Attributes field value if set, zero value otherwise.
func (o *PstreamAddModel) GetAttributes() map[string]interface{} {
	if o == nil || IsNil(o.Attributes) {
		var ret map[string]interface{}
		return ret
	}
	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PstreamAddModel) GetAttributesOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Attributes) {
		return map[string]interface{}{}, false
	}
	return o.Attributes, true
}

// HasAttributes returns a boolean if a field has been set.
func (o *PstreamAddModel) HasAttributes() bool {
	if o != nil && !IsNil(o.Attributes) {
		return true
	}

	return false
}

// SetAttributes gets a reference to the given map[string]interface{} and assigns it to the Attributes field.
func (o *PstreamAddModel) SetAttributes(v map[string]interface{}) {
	o.Attributes = v
}

func (o PstreamAddModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PstreamAddModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.Attributes) {
		toSerialize["attributes"] = o.Attributes
	}
	return toSerialize, nil
}

type NullablePstreamAddModel struct {
	value *PstreamAddModel
	isSet bool
}

func (v NullablePstreamAddModel) Get() *PstreamAddModel {
	return v.value
}

func (v *NullablePstreamAddModel) Set(val *PstreamAddModel) {
	v.value = val
	v.isSet = true
}

func (v NullablePstreamAddModel) IsSet() bool {
	return v.isSet
}

func (v *NullablePstreamAddModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePstreamAddModel(val *PstreamAddModel) *NullablePstreamAddModel {
	return &NullablePstreamAddModel{value: val, isSet: true}
}

func (v NullablePstreamAddModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePstreamAddModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


